# Generated by Django 5.2.6 on 2025-09-30 03:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SnippetCopyLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('copied_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=512)),
                ('referer', models.URLField(blank=True)),
                ('sql_snapshot', models.TextField(blank=True)),
                ('sql_chars', models.PositiveIntegerField(default=0)),
                ('snippet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='copy_logs', to='vault.querysnippet')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-copied_at'],
                'indexes': [models.Index(fields=['copied_at'], name='vault_snipp_copied__e86098_idx')],
            },
        ),
    ]
