# Generated by Django 5.2.6 on 2025-10-02 07:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0002_snippetcopylog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDBAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('db_type', models.CharField(choices=[('postgres', 'PostgreSQL'), ('mysql', 'MySQL/MariaDB'), ('sqlite', 'SQLite'), ('mssql', 'SQL Server'), ('clickhouse', 'ClickHouse'), ('other', 'Other')], max_length=20)),
            ],
        ),
        migrations.AlterModelOptions(
            name='querysnippet',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='querysnippet',
            name='vault_title_lower_idx',
        ),
        migrations.AddField(
            model_name='querysnippet',
            name='sql_kind',
            field=models.CharField(choices=[('select', 'SELECT only'), ('modify', 'INSERT/UPDATE/MERGE'), ('dangerous', 'DELETE/DDL (DROP/ALTER/TRUNCATE/CREATE/GRANT/REVOKE)')], db_index=True, default='select', max_length=16),
        ),
        migrations.AlterField(
            model_name='querysnippet',
            name='db_type',
            field=models.CharField(choices=[('postgres', 'PostgreSQL'), ('mysql', 'MySQL/MariaDB'), ('sqlite', 'SQLite'), ('mssql', 'SQL Server'), ('clickhouse', 'ClickHouse'), ('other', 'Other')], default='mysql', max_length=20),
        ),
        migrations.AlterField(
            model_name='querysnippet',
            name='tags',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='querysnippet',
            name='use_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userdbaccess',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='db_accesses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='userdbaccess',
            unique_together={('user', 'db_type')},
        ),
    ]
